version: '2.1'

services:

    users-db:
        container_name: users-db
        #build: ../flask-microservices-users/project/db
        build:
            #context: https://github.com/KevDi/python_docker.git#master:project/db
            context: ../flask-microservices-users/project/db
        ports:
            - 5435:5432 # expose ports - HOST:CONTAINER
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: exit 0

    users-service:
        container_name: users-service
        build:
            #context: https://github.com/KevDi/python_docker.git
            context: ../flask-microservices-users
        #build: ../flask-microservices-users
        #volumes:
        #    - '../flask-microservices-users:/usr/src/app'
        ports:
            - 5001:5000 # expose ports - HOST:CONTAINER
        environment:
            - APP_SETTINGS=project.config.DevelopmentConfig
            - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
            - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
            - SECRET_KEY=my_precious
        depends_on:
            users-db:
                condition: service_healthy
        links:
            - users-db

    nginx:
        container_name: nginx
        build: ./nginx/
        restart: always
        ports:
            - 80:80
        depends_on:
            users-service:
                condition: service_started
            web-service:
                condition: service_started
        links:
            - users-service
            - web-service

    web-service:
        container_name: web-service
        build: 
        # context: https://github.com/KevDi/flask-microservices-client.git
            context: ../flask-microservices-client
            args:
                - NODE_ENV=development
                - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
        ports:
            - '9000:9000'
        depends_on:
            users-service:
                condition: service_started
        links:
            - users-service
